### ISSUE TITLE
startAssistantControl issue

### ISSUE THREAD

**Issue by ciprian288** [Dimeiza/Assistants#28]
startAssistantControl.sh failed to start
(instaled on RPI B+ fresh raspbian 2018-11-13 )

Listening... Press Ctrl+C to exit
Traceback (most recent call last):
  File "AssistantControl.py", line 96, in <module>
    alexa_mq = posix_ipc.MessageQueue("/AlexaQueue", posix_ipc.O_CREAT)
posix_ipc.PermissionsError: Permission denied

Alexa and Google are working ....
and thank you for your work

**Comment by Dimeiza** [comment]
> alexa_mq = posix_ipc.MessageQueue("/AlexaQueue", posix_ipc.O_CREAT)
> posix_ipc.PermissionsError: Permission denied

It is a permission problem.
(It may be that Assistant control can't create a message queue because Alexa has already created a message queue with root permission)

It seems you ran Alexa(startsample.sh) with **sudo**, like AVS Device SDK installation procedure.

If you so, You can execute:

``
$ sudo rm /dev/mqueue/*
``

And when you execute AssistantControl.sh next time, run Alexa without **sudo**.

``
$ ./startsample.sh
``

**Comment by ciprian288** [comment]
ok...thank you...
