### ISSUE TITLE
GA no audio using respeaker 2mic hat.

### ISSUE THREAD

**Issue by jabulonboaz** [Dimeiza/Assistants#9]
Hi i have alamost finished your build acording to your instructions and i am in the step before instaling it as a service. I am using pi zero w, respeaker 2mic hat and the latest stretch.
I start the 3 terminals, Alexa works fine with audio and LEDs, But GA i see only the LEDs when is say "Snowboy" but no audio. 
Mind you when i run the GA terminal i do get and "iligal instruction" error but i think this is becuse of the SDK detecting the Pi zero ARM processor.
Any ideas why i get no audio on GA?

**Comment by jabulonboaz** [comment]
these are my logs:
pi@raspberrypi:~ $ cd Assistants
pi@raspberrypi:~/Assistants $ ./startGoogleAssistant.sh
./startGoogleAssistant.sh: line 3:  1056 Illegal instruction     googlesamples-a                      ssistant-posixqueue --project-id xxxxxxxxxxxxxxxxxxxx --device-model-id xxxxxxxxxxxxxxxxxxxxxxxxx
pi@raspberrypi:~/Assistants $

**Comment by Dimeiza** [comment]
I guess that you are using old google assisstant sdk.

Try to execute googlesamples-assistant-pushtotalk.
Because:
1. There are several reports that it can run successfully with new sdk in Raspberry Pi Zero.
2. A mechanism of my code(googlesamples-assistant-posixqueue) is almost the same to pushtotalk.

If the same error is displayed, my guess is likely to be correct.

You have to do clean installation of Raspbian. Don't reuse existing Raspbian installed SD card without format.

And install this repository again.

You will spend a lot of time to install google assistant sdk. It is a good sign. Because installation process spend a long time to build grpc environment of Raspberry Pi Zero for Google Assistant SDK.

**Comment by jabulonboaz** [comment]
Hello thank you @Dimeiza 

This the console I used, isn't this the correct one for the latest SDK? 
https://console.developers.google.com/apis/dashboard?project=xxxxxxxxxxxxxxxxxxxxxxxxxxx

I tried and i get the same message:
pi@raspberrypi:~/Assistants/env/bin $ ./googlesamples-assistant-pushtotalk
Illegal instruction
pi@raspberrypi:~/Assistants/env/bin $

When you mention that i have the "old GA SDK" how do mean ? Where do i get the new SDK ?

I did this build from scratch with a fresh copy of stretch and cloned your git as per your instructions. Do you perhaps mean that I have to build a new "product" on the Google developer tool? 

I builded this exactly as per your instructions and on a Pi zero W from scratch, no deviation whatsoever. 

I have used this product with GassistPi and AssistantsPi on P3 and it worked before and still works. 

I have generated this product on the Google assistant tool that is at the same URL as in your instructions "readme" file:
"Google Assistant setup
1. Complete Google Assistant registration.

[Configure a Developer Project and Account Settings] (https://developers.google.com/assistant/sdk/guides/library/python/embed/config-dev-project-and-account).

[Register the Device Model] (https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device#download-credentials)"

The above is an extract from your Git instructions.

Thanks and standing by for your feedback.

**Comment by jabulonboaz** [comment]
"If you follow my instruction, your report is so fast. Did you really follow my instruction?"
I did the build yesterday it took ages to build, i did it clean from start, yes i followed your instructions.\

"I think that the cause of this problem is that Google Assistant does not have binary compatibility between Pi 3 and Pi Zero"
ARMv6 (P1 and Pi zero) processors an not supported any more ether by the AVS device SDK or GA latest SDK this is known yes. that is why your build is very interesting. 

"This repository is eternal PoC, and it is taken for person that can build solely and never need help"
I am an engineer but everyone needs a bit of help some times :) 

Shame you cant help troubleshoot.  
Thank you any way this a very nice work.

**Comment by Dimeiza** [comment]
> Shame you can't help troubleshoot.

I don't mind completely because I have no reason to do troubleshoot for you that isn't my client.

I think that there is no problem even if you can't build this prototype.
Because this repository is informative for someone that can build the prototype. 

> I am an engineer but everyone needs a bit of help some times :)

I agree anyone needs help some times. But I doubt you are an engineer. 

You didn't read any deliverable carefully. 
Even if you insist anything, it is fact several engineers have succeeded to run Alexa or Google Assistant in Pi zero. And you couldn't it.

But don't mind.
You motivated me to share this repository. And I'm proud of this work.

Thanks.

**Comment by Dimeiza** [comment]
Oh, one more thing ...
I forgot it.

I seem that you have already asked a question to other developers that have succeeded to execute Google Assistant with Pi Zero in GitHub.

Nevertheless, if you already can't run Google Assistant in your Pi Zero, there might be caused by your broken hardware(Pi Zero or other hardware). 

Of course, I don't have any responsibility and I don't care whether you can execute Google Assistant in your Pi Zero, but you have a choice that you buy a new Pi Zero and you can try again.

Good luck.

**Comment by jabulonboaz** [comment]
Thanks for taking an interest to look around about my posts in git.

I don’t know if you read it but i told u before the pi0 CPU architecture is not supported by the google SDK any more in headless mode with wakeword detection. The only thing that works is push to talk with the push button, that i know and there are many examples on the git with the push button. Also Amazon is not supporting the ARMv6 CPU in the latest device SDK ether for that matter. 
I have not come across anyone that has done what u done with the Google SDK and wakeword detection. That is why i decided to try your build and again its a very nice work.

I have another pi zero i can try with another one maybe its bad HW like you say but i doubt it because Alexa works fine with your build on the same device. I mentioned this before too but you said its not important, i have done many builds including GassistPi and Google SDK and AssistantsPi etc and its always the same result. Alexa works on Pi0 (with the old SDK) but Google assistant works only on Pi3.

This is on a more personal note. Whether you doubt the fact that i am an engineer or not its irrelevant, the open community of the git is based on all of us helping each other and enjoying. Yes you should be proud of your work but if i were you i would not be so proud of my attitude. There is not need for rudeness on the open community and once  you publish something you should expect some questions this is normal and you can choose not to answer thst is fine but being rude that is not cool. I have been working in the tech industry for over 15 years i am a HW engineer by background but i am not a SW engineer, my questions are purely because i like voice A.I. and to build stuff for fun.

Again in conclusion there are many instances on forums where others had the “illegal instruction” error i get on GA SDK build on a pi0 headless mode so i dont know what you did and you managed to do that but congratulations and feel free to point me to any other git that has this implemented too so i can study it.
https://github.com/google/aiyprojects-raspbian/issues/177

https://github.com/shivasiddharth/GassistPi/issues/180

The above is my post on GassistPi git and you can see the devs answer that says its not supported that is why i was so curious about your build.
Also if you read on GA official SDK site it says they only support ARMv7 CPU architecture.  

In any case thank you for your time so far and remember be cool no need to “doubt” anyone we are not all SW developers here.         

Again very nice work i like what you achived.

**Comment by Dimeiza** [comment]
I seem that you didn't try again.

You have already noticed difference between hotword and pushtotalk. And If you noticed I mentioned before, It may can be possible to understand a mechanism of this protototype, and you probably can run it.

> 2. A mechanism of my code(googlesamples-assistant-posixqueue) is almost the same to pushtotalk.

But your choice is your own. You can choice what you prefer.

For your information:
I'm put on the desk a prototype(Pi Zero) built by this repository. It can respond to use Google Assistant now. This prototype is built in 3/25/2018.

I understood your backgrond. It is good chance that  write my attitude.

I think that your action of GitHub is question-only.
I seem that you haven't publish something in open source community, and I seem you don't understand a effort of developer published something.

Questioning in GitHub is so easy but answering it in GitHub is costable. Most developer have a day job and they respond a question  as volunteer activity.

You have already understood there are many kinds of engineer in GitHub. In addition you need to know there is not only a native speaker of english. Such as me. 

A task of technical inspection requires long time, in addition, non-native speaker needs translatate for answering a question.

You report already for my instruction in this issue about clean install.

I have seen a problem of "Illegal instruction" before in my envionment . and I already have known this is caused by failing to build grpc environment(for instance: It is occur by using a binary that be built in Pi3) . Therefore I suggested you follow above instruction and this task need a time and I estimated half a day.

But you have reported for 3 hours later:

> I tried and i get the same message:
pi@raspberrypi:/Assistants/env/bin $ ./googlesamples-assistant-pushtotalk
Illegal instruction
pi@raspberrypi:/Assistants/env/bin $

This is sign that grpc build failed. If grpc is built properly in Pi Zero(as same as I built before), This message don't appear.

As timing of your report, It was so fast than I estimated, I thought you didn't follow my instruction properly.

In other issue, you didn't follow basic instruction of  Alexa Device SDK official document that everyone followed.

And if anyone didn't create what your prefer, you can build your own, and should it. You can also read codes of this repository to find out a mechanism, If you didn't have skill, inspect your own and share your all result. These are engineer's attitude regardless of whether open source community or not. But your actions are opposite above.It is customer's attitude.

These are why I thought you aren't an engineer.

I understood that you think developer should expect question and shall polite. You can use this attitude for your deliverable. But I don't use this attitude especially in this repository.

As I have written in README, This repository is for power user, and should be used at own risk. It is attempted to give information for method to build Assistants. It is not more than that.

I prefer suggestion for improvements but I don't hope question for executing in someone environment.

It is mistake of me that I didn't wrote this attitude in README.

But I hope you understand above thinking, especially:

1. Policy on deliverables is different between each engineer.
2. Cost of answering question mey be high more than questioning.
3. If you don't satisfy existing software, you should make what you prefer.

I don't hope your reply because any further interaction is not informative and is not valuable. 

Thanks.

**Comment by jabulonboaz** [comment]
Hello i have to tell you i took the SD card out of the pi 0 and put it in the pi3 same SD card same build as before and both assistants work. When i put it back in the pi0 only Alexa works and for Google Assistant i get "illegal instruction" but not when  i put it in p3. 
This confirms my original remark about GA not being able to run on pi 0 because it uses an ARMv6 CPU SoC.
Again brilliant work but if i were you i would try building it again today see if u get the same "illegal instruction" error on pi zero. 
This just FYI i am not after help.

Thanks again.

**Comment by Dimeiza** [comment]
I understood your issue.
I tried to build from clean install today, and I confirmed "Illegal Instruction" message you said.

It is my mistake I didn't treat properly your report.

And I have already grasped almost a cause. It is not caused your said. It may be caused by changed installation procedure of grpcio pip package. 

As a principle, Google Assistant without wakeword function is designed that can execute in Pi Zero. Because Google Assisant over grpc(It is called "Google Assistant Service") has been enable in all grpc platform. This fact is written by right row of table "Compatibility and feature support" in official document. 

https://developers.google.com/assistant/sdk/overview

It is also clear from this news:
https://www.theverge.com/circuitbreaker/2018/4/16/17244802/google-diy-aiy-machine-learning-vision-kit-voice-kit-project-update

Because AIY voice kit that uses google assistant can execute in Pi Zero.

I think that Google must solve this problem, but I found out a candidate of solution of this problem and I'm trying it now.

**Comment by jabulonboaz** [comment]
@Dimeiza i read the news about AIY new build 2 days ago that is a different built and i wanted to let u know about it too. I believe AIY latest image will work with hotword on pi0 now i will try it on the weekend. 

The illegal instruction issue is on the classic device SDK with hotword but the pushbutton always worked with pi0 in the past and it shuld now too.

In any case thank u and your brilliant work is still very good.

Here is a link of the SD img for the latest AIY that should work with hotword on pi0
  https://dl.google.com/dl/aiyprojects/aiyprojects-latest.img.xz

**Comment by Dimeiza** [comment]
https://github.com/googlesamples/assistant-sdk-python/issues/235

**Comment by jabulonboaz** [comment]
Thank you i have been following that stream that is very good. I guess u have to do the build form the beginning now. I will start and report back.
